{
  "formatVersion": "1.1",
  "component": {
    "group": "nullversionnova",
    "module": "plugin",
    "version": "0.0.35",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-0.0.35.jar",
          "url": "plugin-0.0.35.jar",
          "size": 22050,
          "sha512": "049cac57ed3847d6e91a61fe4ab080c304ed2ef21737d87f13867778507cc66f865301483ebe93d8c2677d1590c461f424da767a6964e1236741d80bfa77dfd1",
          "sha256": "a206731b5224f0207c9e4fbdad86865d4fb093a2a589d1e50f84915180963e58",
          "sha1": "1189af3b82dbf32ef8d49db2d60b54f3ba333b67",
          "md5": "616b6f5dcf11067400910707c97a0a9f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.10"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-0.0.35.jar",
          "url": "plugin-0.0.35.jar",
          "size": 22050,
          "sha512": "049cac57ed3847d6e91a61fe4ab080c304ed2ef21737d87f13867778507cc66f865301483ebe93d8c2677d1590c461f424da767a6964e1236741d80bfa77dfd1",
          "sha256": "a206731b5224f0207c9e4fbdad86865d4fb093a2a589d1e50f84915180963e58",
          "sha1": "1189af3b82dbf32ef8d49db2d60b54f3ba333b67",
          "md5": "616b6f5dcf11067400910707c97a0a9f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "plugin-0.0.35-javadoc.jar",
          "url": "plugin-0.0.35-javadoc.jar",
          "size": 261,
          "sha512": "c0e2455a3987345e07e94af6c40d913fa28c3737fa63cb461b620f5f99ded397246980eef60d5a5f69454d9a2425ae7dac1254785228fc43bde69273682d8f13",
          "sha256": "038acff6fd5f04308bb06d49d9d6c4a1ffeefd072d3d256409924cec976b6255",
          "sha1": "93415949d39ccb2fac6cb14861a34e02861def38",
          "md5": "9f14205ecf6515589242e5cc213cfa24"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "plugin-0.0.35-sources.jar",
          "url": "plugin-0.0.35-sources.jar",
          "size": 3086,
          "sha512": "efaf8bba039624ef33d0dd697ae4ca0933e12c415b739aea88ec8dda33a8b3dca82970a5ce4c9cfe6a97f134109c2978f994d8a0e38f36510d61aef8d07b6e80",
          "sha256": "5fbc3a300d01d640d8aabd394f51baeb8dd951aff415bbd78ee6c68922c45fd4",
          "sha1": "cde37ad38b75ddf430231bbe889ec06ec6f5434c",
          "md5": "504804eb9c6a0fd3fac97615eb58261a"
        }
      ]
    }
  ]
}
