{
  "formatVersion": "1.1",
  "component": {
    "group": "nullversionnova",
    "module": "preprocessor",
    "version": "SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "preprocessor-SNAPSHOT.jar",
          "url": "preprocessor-SNAPSHOT.jar",
          "size": 144333,
          "sha512": "926ab5ed37bd3d484b915fd5e97a25ddf32d417d8d6f34c3634bab83dbe05222528994a9a60001f3b540bc2b7d933e116313386a0976d5f2c701b5e5ad71792a",
          "sha256": "e45e798129f3e7b9bbf745ca08554d72e7594288b3ec9086d92fab01f3492249",
          "sha1": "2f5a21904229f33470ccde95ed9e58c92fcbf02a",
          "md5": "47eeb9aec053e80c62817add0ed374de"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.replaymod",
          "module": "remap",
          "version": {
            "requires": "3a12dc2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "tiny-mappings-parser",
          "version": {
            "requires": "0.2.1.13"
          }
        }
      ],
      "files": [
        {
          "name": "preprocessor-SNAPSHOT.jar",
          "url": "preprocessor-SNAPSHOT.jar",
          "size": 144333,
          "sha512": "926ab5ed37bd3d484b915fd5e97a25ddf32d417d8d6f34c3634bab83dbe05222528994a9a60001f3b540bc2b7d933e116313386a0976d5f2c701b5e5ad71792a",
          "sha256": "e45e798129f3e7b9bbf745ca08554d72e7594288b3ec9086d92fab01f3492249",
          "sha1": "2f5a21904229f33470ccde95ed9e58c92fcbf02a",
          "md5": "47eeb9aec053e80c62817add0ed374de"
        }
      ]
    }
  ]
}
